typography_spectrum: 0.2650034031830728
content_rating:
  adult: false
color:
  brandStrength: 0.2099064278881997
  lightness: 0.5681494136806577
  saturation: 0.7256603410933167
  rhythmicContrast: 0.5712156649678946
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.9847071850672364
author:
  name: Lucas
  email: luc_sigouin@hotmail.com
  url: lucsigouin.com
name: lucsigouin
navigation: []
title: in the mind of a tech lover
description: think of what i'm thinking
